version: 1

formatters:
    standard:
        format: "%(asctime)s | %(levelname)s | %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: standard
    file:
        class: logging.handlers.TimedRotatingFileHandler
        level: INFO
        formatter: standard
        filename: logs/app.log
        when: midnight
        backupCount: 7
        encoding: utf-8

loggers:
    # root logger
    "":
        level: INFO
        handlers: [console, file]
    
    # handlers=[] and propagate=false turns this logger off
    "uvicorn.access":
        handlers: []
        propagate: false
    
    # having this logger just propagate to root doesn't seem to work
    "uvicorn.error":
        handlers: [console, file]
        propagate: false